server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service   
          predicates:
            - Path=/usuario/**
                - id: usuario-service
          uri: lb://coche-service   
          predicates:
            - Path=/coche/**
                - id: usuario-service
          uri: lb://moto-service   
          predicates:
            - Path=/moto/**    